version: '3.7'

services:
  kaitokid-blog:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: kaitokid-blog
    restart: unless-stopped
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    networks:
      - kaitokid-blog-network

  kaitokid-blog-db:
    image: mysql:8.0.32
    container_name: kaitokid-blog-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=kaitokid_blog
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
    networks:
      - kaitokid-blog-network

  kaitokid-blog-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kaitokid-blog-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=kaitokid-blog-db
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=admin
    networks:
      - kaitokid-blog-network

networks:
  kaitokid-blog-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
